### ISSUE TITLE
sort out the mongo db table layout for file signatures

### ISSUE THREAD

**Issue by tianyin** [tianyin/rekcod#13]
decide the table layout: what are the metadata we need except the general statistics. 
Currently, `fsaudit` only returns a `dict` with the key as the file path and the value as the md5.

**Comment by tianyin** [comment]
@EvonX note that the key is the md5 value. 
essentially, the key is a `file` (which is an abstraction) which is identified by its md5 value.

**Comment by EvonX** [comment]
add `db.rekcod_db.filesig_insert_or_update(imgname, file_md5s)` which inserts the file sigs of an image into mongodb collection `rekcod.file_sigs`. `file_sigs` has following format:
```
{ u'count': 1,
 u'filepath_count': {u'/usr/share/mime/audio/x-riff\\u002exml': 1},
 u'imgname_count': {u'centos:7': 1},
 u'md5': u'e15b587fc57d5d402dd61a1c90773a5b'
}
```

**Comment by EvonX** [comment]
I tried inserting centos file sigs to mongodb and found that centos has many duplicated files: only `8748` unique md5 for `33082` file path. Following is top repeated md5 and the repeated times:
```
6663 897316929176464ebc9ad085f31e7284
1414 3c703600d3cb906f6c7b80f9e2a56bde
1087 d41d8cd98f00b204e9800998ecf8427e
760 b026324c6904b2a9cb4b88d6d61c81d1
731 451e20aff0f489cd2f7d4d73533aa961
695 df890775556f1491b2a6bec6313296f4
586 68b329da9893e34099c7d8ad5cb9c940
517 30c51c08d5947cfa5adcfa563e78c8ae
180 db5c3c9d348ce26169c56901a7606961
165 919d117956d3135c4c683ff021352f5c
159 26ab0db90d72e28ad0ba1e22ee510510
158 1dcca23355272056f04fe8bf20edfce0
144 65e68c729f08e83399fc12ef6c30414c
143 7ba34a7c9344df2acabdb0146b9e15e3
143 8f14e45fceea167a5a36dedd4bea2543
143 d8d8a6d2e9e1fb99302b479a8fe540d4
143 9cfefed8fb9497baa5cd519d7d2bb5d7
138 c30f7472766d25af1dc80b3ffc9a58c7
131 2254342becceafbd04538e0a38696791
128 747a43298e195448246825207a9364b6
115 c6f121a71bcc7e38aafdc26862a48e81
115 26993a377e50112fae1b024b54fd9519
115 aa1fc3398e84bda331b47203c1e53ad5
115 47214fbd0b6c5ef654b9856c20464f3e
104 2c1e50a164e562cd9737b1c81ebf3148
103 a1f03e46f8ad817f8fdd47b8b2f767a5
101 9caff0735bc6e80121cedcb98ca51821
95 0c3f86606761f1ff7ee29e806a375486
76 fe7d81814e02eb1296757e75bb3c6be9
74 0f38d1a543b96eb8d34b6fcdc9227445
```

**Comment by tianyin** [comment]
are you sure? 
`8748/33082 = 26.4%`
It's too good to be true...

**Comment by tianyin** [comment]
@EvonX can you look into why so many different file path has the same file content?

It's definitely an interesting, *exciting* finding. 

~t

**Comment by tianyin** [comment]
also, the current table structure seems cannot reflect the information on a single image.
for example, if one file occurs 10 times on one image, how is the value in the table?

~t

**Comment by EvonX** [comment]
@tianyin Yes, I'm pretty sure the number. I manually `wc` the top repeated md5s in the cenos sig files from you and it shows the same count.

I also looked into the corresponding content of the top repeated md5s, and it seems somehow reasonable, as follows:

| count | md5                              | content            | example path                                                        |
|-------|----------------------------------|--------------------|---------------------------------------------------------------------|
| 6663  | 897316929176464ebc9ad085f31e7284 | 0                  | /sys/kernel/slab/inode_cache/reserved                               |
| 1414  | 3c703600d3cb906f6c7b80f9e2a56bde | disabled           | /sys/devices/system/memory/memory9/power/async                      |
| 1087  | d41d8cd98f00b204e9800998ecf8427e | \empty            | /sys/devices/system/memory/memory42/uevent                          |
| 760   | b026324c6904b2a9cb4b88d6d61c81d1 | 1                  | /sys/kernel/slab/sighand_cache/destroy_by_rcu                       |
| 731   | 451e20aff0f489cd2f7d4d73533aa961 | auto               | /sys/devices/virtual/misc/fuse/power/control                        |
| 695   | df890775556f1491b2a6bec6313296f4 | unsupported        | /sys/devices/virtual/mem/port/power/runtime_status                  |
| 586   | 68b329da9893e34099c7d8ad5cb9c940 | \n                 | /sys/devices/platform/serial8250/tty/ttyS14/power/wakeup_max_time_m |
| 517   | 30c51c08d5947cfa5adcfa563e78c8ae | 0x0000000000000000 | /sys/module/bridge/sections/__mcount_loc                            |

We can definitely bypass many files from those directories, i.e. `/sys/kernel`, `/sys/devices`, `/sys/module`, etc. Or we can even bypass the md5s since those simple contents are unlikely to perform malicious behavior alone.

**Comment by tianyin** [comment]
I see. most of them are those dynamic information. 
#16 should be able to ignore the files, which has the benefit of even accelerate the audit process.

With ~8000 files per image, it's a great potential for us.

**Comment by EvonX** [comment]
Insert the 121 image fs_sigs in dir `fssigs` into mongo collection `rekcod.file_sigs`. 
The collection format is as follows:
```
{ u'filepath_count': 3,     #how many unique files have this md5
 u'filepaths': {u'/usr/lib64/perl5/auto/Math/BigInt/FastCalc/FastCalc\\u002eso': 3},    #how many times each unique file occurs
 u'imgname_count': 3,     #how many unique images have this md5
 u'imgnames': {u'tyrellsys\\u002eamazonlinux-httpd24:create-httpd-compile-env': 1,  
  u'tyrellsys\\u002eamazonlinux-httpd24:latest': 1,
  u'tyrellsys\\u002eamazonlinux-httpd24:ticket_41500_2': 1},   #how many times each unique imgname occurs
 u'md5': u'c7a68c94bd220ac34289a8aab25ef412'
}
```
The 121 images generate totally `193371` md5s and `114855` md5s just appear in 1 images. I will look into those `114855` files to see what cause the difference.

**Comment by tianyin** [comment]
@cutylewiwi is in full charge of this. 
thanks!
